const express = require('express');
const router = express.Router();

// Import all route modules
const index = require('./index');
const auth = require('./auth');
const category = require('./category');
const product = require('./product');
const sku = require('./sku');
const shop = require('./shop');
const banner = require('./banner');
const activity = require('./activity');
const alert = require('./alert');
const message = require('./message');
const user = require('./user');
const upload = require('./upload');
const order = require('./order');
const address = require('./address');
const wallet = require('./wallet');
const bank = require('./bank');
const recharge = require('./recharge');
const withdraw = require('./withdraw');
const favorite = require('./favorite');
const authRefresh = require('./authRefresh');
const cms = require('./cms');
const notification = require('./notification');
const review = require('./review');
const storeGoods = require('./storeGoods');
const userGoods = require('./userGoods');
const userShop = require('./userShop');
const kefu = require('./kefu');
const trade = require('./trade');
const amount = require('./amount');
const shipping = require('./shipping');
const admin = require('./admin');
const coupon = require('./coupon');
const payment = require('./payment');
const paymentSettings = require('./paymentSettings');
const imageProxy = require('./imageProxy');
const backup = require('./backup');
const report = require('./report');
const settings = require('./settings');
const session = require('./session');
const submission = require('./submission');

// Register all routes
router.use('/main/index', index);
router.use('/main/sendMsg', auth);
router.use('/main/user', auth);
router.use('/main/goodsCategory', category);
router.use('/main/goods', product);
router.use('/main/goodsSku', sku);
router.use('/main/userShop', shop);
router.use('/main/banner', banner);
router.use('/main/activity', activity);
router.use('/main/msg', alert);
router.use('/main/userMsg', message);
router.use('/main/lang', index);
router.use('/main/countryArea', auth);

router.use('/home/user', user);
router.use('/home/upload', upload);
router.use('/home/userOrder', order);
router.use('/home/userAddress', address);
router.use('/home/userWallet', wallet);
router.use('/home/userBank', bank);
router.use('/home/userRecharge', recharge);
router.use('/home/userWithdraw', withdraw);
router.use('/home/userCollect', favorite);
router.use('/home/auth', authRefresh);
router.use('/home/cms', cms);
router.use('/home/notification', notification);
router.use('/home/goodsReviews', review);
router.use('/home/goods', storeGoods);
router.use('/home/userGoods', userGoods);
router.use('/home/userShop', userShop);
router.use('/home/userKefu', kefu);
router.use('/home/trade', trade);
router.use('/home/userAmount', amount);
router.use('/api/alert', alert);
router.use('/home/shipping', shipping);
router.use('/home/admin', admin);
router.use('/home/admin/coupons', coupon);
router.use('/home/userOrder/coupon', coupon);
router.use('/home/payment', payment);
router.use('/home/payment-settings', paymentSettings);
router.use('/home/image', imageProxy);
router.use('/home/admin', backup);
router.use('/home/report', report);
router.use('/home/admin/settings', settings);
router.use('/home/session', session);
router.use('/home', submission);

module.exports = router;